name: Qt WebAssembly Build and Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Install Emscripten (WASM Compiler)
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: '3.1.25'

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.5.3'
          target: 'desktop'
          architecture: 'wasm_32'
          cache: 'true'

      - name: Build Project
        run: |
          mkdir build
          cd build
          qmake ../2048.pro
          make

      - name: Prepare Files for Deployment
        run: |
          mkdir -p public
          cp build/*.wasm public/
          cp build/*.js public/
          cp build/*.html public/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          force_orphan: true
